services:
    backend-express:
        container_name: putra_tickitz
        image: oktaviandwip/tickitz:6
        restart: unless-stopped
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=ep-tiny-cell-a1mf3ge6.ap-southeast-1.aws.neon.tech
            - DB_USER=tickitz_owner
            - DB_NAME=tickitz
            - DB_PASSWORD=x4ihbJdD7BMt
            - DB_PORT=5432